### ISSUE TITLE
I met a bug when I run

### ISSUE THREAD

**Issue by TriBall3** [HaojHuang/Equivariant-Transporter-Net#1]
When I run:
`python train.py --equ --lite --angle_lite --task=block-insertion --n_demos 1 --interval 200 --n_step 1000 --init`
I met a problem below, How can I solve this ?
>(etn) randy@randy-Precision-7920-Tower:/media/randy/299D817A2D97AD94/FTY/Equivariant-Transporter-Net-main$ python train.py --equ --lite --angle_lite --task=block-insertion --n_demos 1 --interval 200 --n_step 1000 --init
2022-03-25 12:56:58.160504: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
pybullet build time: Dec  1 2021 18:33:04
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from networks.non_equi_transporter import TransporterAgent as non_equi_agent
  File "/media/randy/299D817A2D97AD94/FTY/Equivariant-Transporter-Net-main/networks/non_equi_transporter.py", line 12, in <module>
    from non_equi_transport import Transport
  File "/media/randy/299D817A2D97AD94/FTY/Equivariant-Transporter-Net-main/networks/non_equi_transport.py", line 11, in <module>
    import kornia as K
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/kornia/__init__.py", line 10, in <module>
    from . import (
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/kornia/augmentation/__init__.py", line 54, in <module>
    from kornia.augmentation.container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/kornia/augmentation/container/__init__.py", line 1, in <module>
    from kornia.augmentation.container.augment import AugmentationSequential
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/kornia/augmentation/container/augment.py", line 20, in <module>
    from kornia.geometry.boxes import Boxes
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/kornia/geometry/boxes.py", line 464, in <module>
    @torch.jit.script
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/__init__.py", line 818, in script
    ast = get_jit_class_def(obj, name)
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 143, in get_jit_class_def
    self_name=self_name) for method in methods]
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 143, in <listcomp>
    self_name=self_name) for method in methods]
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 158, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 198, in build_def
    build_stmts(ctx, body))
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 122, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 122, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 174, in __call__
    return method(ctx, node)
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 332, in build_If
    build_stmts(ctx, stmt.body),
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 122, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 122, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 174, in __call__
    return method(ctx, node)
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 288, in build_Raise
    expr = build_expr(ctx, stmt.exc)
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 174, in __call__
    return method(ctx, node)
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 405, in build_Call
    args = [build_expr(ctx, py_arg) for py_arg in expr.args]
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 405, in <listcomp>
    args = [build_expr(ctx, py_arg) for py_arg in expr.args]
  File "/home/randy/anaconda3/envs/etn/lib/python3.7/site-packages/torch/jit/frontend.py", line 173, in __call__
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: JoinedStr aren't supported
def __init__(
    self, boxes: torch.Tensor, raise_if_not_floating_point: bool = True,
    mode: str = "xyzxyz_plus"
) -> None:
    if not isinstance(boxes, torch.Tensor):
        raise TypeError(f"Input boxes is not a Tensor. Got: {type(boxes)}.")
                        ~ <--- HERE

    if not boxes.is_floating_point():
        if raise_if_not_floating_point:
            raise ValueError(f"Coordinates must be in floating point. Got {boxes.dtype}.")

        boxes = boxes.float()

    if len(boxes.shape) == 0:
        # Use reshape, so we don't end up creating a new tensor that does not depend on

**Comment by HaojHuang** [comment]
Cannot repeat
